In [ ]:
#!/usr/bin/env python
import numpy as np

seq_2 = "GAATC"
seq_1 = "CATAC"

# A:A, C:C, etc get +1
# any mismatch gets -1
subst_matrix = {
'A': {'A': 10,'C':-5,'G':0,'T':-5},
'C': {'A':-5,'C': 10,'G':-5,'T':0},
'G': {'A':0,'C':-5,'G': 10,'T':-5},
'T': {'A':-5,'C':0,'G':-5,'T': 10},
}
coordinates=["g,c","a,c","a,c","t,c","c,c","g,a","a,a","a,a","t,a","c,a","g,t","a,t","a,t","t,t","c,t","g,a","a,a","a,a","t,a","c,a","g,c","a,c","a,c","t,c","c,c"]
gap_penalty = -4
directions={}
steps=[]
# this will store our dynamic programming matrix
dp_matrix = np.ndarray(shape=(len(seq_1)+1,len(seq_2)+1), dtype=int)
dp_matrix.fill(0)
diagonal={}
count=0
# fill the DP matrix
for i in range(len(seq_1)+1):
    for j in range(len(seq_2)+1):
        if i==0 and j==0: continue # skip the first cell

        char_1 = seq_1[i-1] # current character at seq 1
        char_2 = seq_2[j-1] # current character at seq 2

        #
        # YOUR TASK: 'scores' must be filled in here
	# HINTS:
	#  * refer to the previous (e.g. diagonal predecessor) cell as dp_matrix[i-1,j-1]
	#  * get the substitution score as subst_matrix[char_1][char_2]
        #  * the gap score is called gap_penalty (these variables are defined above)
	#
        scores = [-999,-999,-999]
        if( i>0 and j>0 ):
#             # score diagonal
            scores[0] = dp_matrix[i-1,j-1] + subst_matrix[char_1][char_2]
            directions["diagonal"]=dp_matrix[i-1,j-1] + subst_matrix[char_1][char_2]
#         for keys in diagonal:
#             diagonal[scores[0]]='d'
#             print("ll",diagonal)

            #print("diagonal/////",scores[0])
            #print(diagonal)
            pass
        if( i>0 ):
            # score up: gap in sequence 2
            scores[1] = dp_matrix[i-1,j] + gap_penalty
            directions["up"]=dp_matrix[i-1,j] + gap_penalty
            #for i in (scores)
            #print("up/////",scores[1])
            pass
        if( j>0 ):
            # score left: gap in sequence 1
            scores[2] = dp_matrix[i,j-1] + gap_penalty
            directions["left"]=dp_matrix[i,j-1] + gap_penalty
            #print("left/////",scores[2])
            pass
        MAX=-9000
        for z in directions:
            if(directions[z]>MAX):
                MAX=directions[z]
        for zz , jj in directions.items():
            if (jj == MAX):
                steps.append(zz)
        print(scores)
        #print(scores[0],scores[1],scores[2],"g,c")
        # select the best previous cell
        difference=scores[0]-scores[1]-scores[2]
        #if ((scores[0] == scores[2]) or (scores[0]==scores[1]):
        best = max(scores)
        dp_matrix[i,j]=best
#         if (difference < -800):
#             continue
#         else:
#             best_index=max(scores)
#             INDEX=scores.index(best_index)
#             if (INDEX==0):
#                 directions.append("diagonal")
#             elif(INDEX==1):
#                 directions.append("up")
#             elif(INDEX==2):
#                 directions.append("Left")
        #best = max(scores)
        count+=1
#         for i in best:
#             diagonal[i]=coordinates[i]
        #dp_matrix[i,j]=best
#print("ll",diagonal)
#print("////",diagonal)
print("Dynamic programming matrix:")
print(dp_matrix)
print(directions)
print("///////////")
print(len(directions))
print(count)


print(steps)
print("len",len(steps))
# Best score for global allignment

print("best sore",best)

[-999, -999, -4]
[-999, -999, -8]
[-999, -999, -12]
[-999, -999, -16]
[-999, -999, -20]
[-999, -4, -999]
[-5, -8, -8]
[-9, -12, -9]
[-13, -16, -13]
[-12, -20, -17]
[-6, -24, -16]
[-999, -8, -999]
[-4, -9, -12]
[5, -13, -8]
[1, -17, 1]
[-18, -16, -3]
[-17, -10, -7]
[-999, -12, -999]
[-13, -8, -16]
[-9, 1, -12]
[0, -3, -3]
[11, -7, -4]
[-3, -11, 7]
[-999, -16, -999]
[-12, -12, -20]
[2, -3, -16]
[11, -4, -2]
[-5, 7, 7]
[6, 3, 3]
[-999, -20, -999]
[-21, -16, -24]
[-17, -2, -20]
[-3, 7, -6]
[11, 3, 3]
[17, 2, 7]
Dynamic programming matrix:
[[  0  -4  -8 -12 -16 -20]
 [ -4  -5  -9 -13 -12  -6]
 [ -8  -4   5   1  -3  -7]
 [-12  -8   1   0  11   7]
 [-16 -12   2  11   7   6]
 [-20 -16  -2   7  11  17]]
{'left': 7, 'up': 2, 'diagonal': 17}
///////////
3
35
['left', 'left', 'left', 'left', 'left', 'up', 'diagonal', 'left', 'diagonal', 'left', 'diagonal', 'diagonal', 'diagonal', 'diagonal', 'diagonal', 'diagonal', 'left', 'diagonal', 'left', 'left', 'left', 'up', 'up', 'diagonal', 'diagonal', 'le

In [ ]:
seq_2 = "GAATC"
seq_1 = "CATAC"

# LOCAL ALLIGNMENT

In [ ]:
#!/usr/bin/env python
import numpy as np

seq_2 = "GAATC"
seq_1 = "CATAC"

# A:A, C:C, etc get +1
# any mismatch gets -1
subst_matrix = {
'A': {'A': 10,'C':-5,'G':0,'T':-5},
'C': {'A':-5,'C': 10,'G':-5,'T':0},
'G': {'A':0,'C':-5,'G': 10,'T':-5},
'T': {'A':-5,'C':0,'G':-5,'T': 10},
}
gap_penalty = -4
directions={}
steps=[]

# this will store our dynamic programming matrix
dp_matrix = np.ndarray(shape=(len(seq_1)+1,len(seq_2)+1), dtype=int)
dp_matrix.fill(0)


# fill the DP matrix
for i in range(len(seq_1)+1):
    for j in range(len(seq_2)+1):
        if i==0 and j==0: continue # skip the first cell

        char_1 = seq_1[i-1] # current character at seq 1
        char_2 = seq_2[j-1] # current character at seq 2

        #
        # YOUR TASK: 'scores' must be filled in here
	# HINTS:
	#  * refer to the previous (e.g. diagonal predecessor) cell as dp_matrix[i-1,j-1]
	#  * get the substitution score as subst_matrix[char_1][char_2]
        #  * the gap score is called gap_penalty (these variables are defined above)
	#
        scores = [-999,-999,-999,0]
        if( i>0 and j>0 ):
#             # score diagonal
            scores[0] = dp_matrix[i-1,j-1] + subst_matrix[char_1][char_2]
            directions["diagonal"]=dp_matrix[i-1,j-1] + subst_matrix[char_1][char_2]
            pass
        if( i>0 ):
            # score up: gap in sequence 2
            scores[1] = dp_matrix[i-1,j] + gap_penalty
            directions["up"]=dp_matrix[i-1,j] + gap_penalty
            pass
        if( j>0 ):
            # score left: gap in sequence 1
            scores[2] = dp_matrix[i,j-1] + gap_penalty
            directions["left"]=dp_matrix[i,j-1] + gap_penalty
            pass
            MAX=-9000
        for z in directions:
            if(directions[z]>MAX):
                MAX=directions[z]
        for zz , jj in directions.items():
            if (jj == MAX):
                steps.append(zz)
        print(scores)
        # select the best previous cell
        best = max(scores)
        dp_matrix[i,j]=best
#         if (best < 0):
#             best = 0
print("Dynamic programming matrix:")
print(dp_matrix)

# best score for local allignment
print(steps)
print("best score",best)

[-999, -999, -4, 0]
[-999, -999, -4, 0]
[-999, -999, -4, 0]
[-999, -999, -4, 0]
[-999, -999, -4, 0]
[-999, -4, -999, 0]
[-5, -4, -4, 0]
[-5, -4, -4, 0]
[-5, -4, -4, 0]
[0, -4, -4, 0]
[10, -4, -4, 0]
[-999, -4, -999, 0]
[0, -4, -4, 0]
[10, -4, -4, 0]
[10, -4, 6, 0]
[-5, -4, 6, 0]
[-5, 6, 2, 0]
[-999, -4, -999, 0]
[-5, -4, -4, 0]
[-5, 6, -4, 0]
[5, 6, 2, 0]
[20, 2, 2, 0]
[6, 2, 16, 0]
[-999, -4, -999, 0]
[0, -4, -4, 0]
[10, 2, -4, 0]
[16, 2, 6, 0]
[1, 16, 12, 0]
[15, 12, 12, 0]
[-999, -4, -999, 0]
[-5, -4, -4, 0]
[-5, 6, -4, 0]
[5, 12, 2, 0]
[16, 12, 8, 0]
[26, 11, 12, 0]
Dynamic programming matrix:
[[ 0  0  0  0  0  0]
 [ 0  0  0  0  0 10]
 [ 0  0 10 10  6  6]
 [ 0  0  6  6 20 16]
 [ 0  0 10 16 16 15]
 [ 0  0  6 12 16 26]]
['left', 'left', 'left', 'left', 'left', 'left', 'up', 'left', 'up', 'left', 'up', 'left', 'up', 'diagonal', 'diagonal', 'diagonal', 'diagonal', 'diagonal', 'diagonal', 'left', 'up', 'left', 'up', 'up', 'up', 'diagonal', 'left', 'left', 'diagonal', 'diagonal', 'diagon

In [ ]:
seq_2 = "GAATC"
seq_1 = "CATAC"


## understand the above code

In [ ]:
# to understand char_1, skip the first cell which filled by zero and begin with the real sequence
for j in range(len(seq_2)+1):
    if j==0: continue # skip the first cell

    char_1 = seq_2[j-1] # current character at seq 1
    print(char_1)

G
A
A
T
C


In [ ]:
# to understand the substitution matrix of char_1, skip the first cell which filled by zero and begin with the real sequence
for j in range(len(seq_2)+1):
    if j==0: continue # skip the first cell

    char_1 = seq_2[j-1] # current character at seq 1
    print(char_1)
    print(subst_matrix[char_1])

G
{'A': 0, 'C': -5, 'G': 10, 'T': -5}
A
{'A': 10, 'C': -5, 'G': 0, 'T': -5}
A
{'A': 10, 'C': -5, 'G': 0, 'T': -5}
T
{'A': -5, 'C': 0, 'G': -5, 'T': 10}
C
{'A': -5, 'C': 10, 'G': -5, 'T': 0}


In [ ]:
# determine ch_1 and ch_2 in substitution matrix
for i in range(len(seq_1)+1):
    for j in range(len(seq_2)+1):
#         if i==0 and j>0: dp_matrix[i,j*gap_penalty]
#         if i>0 and j==0: dp_matrix[i*gap_penalty,j]
        if i==0 and j==0: continue # skip the first cell
        char_1 = seq_1[i-1] # current character at seq 1
        char_2 = seq_2[j-1] # current character at seq 2
        print(char_1,char_2)
        print(subst_matrix[char_1][char_2])

C G
-5
C A
-5
C A
-5
C T
0
C C
10
C C
10
C G
-5
C A
-5
C A
-5
C T
0
C C
10
A C
-5
A G
0
A A
10
A A
10
A T
-5
A C
-5
T C
0
T G
-5
T A
-5
T A
-5
T T
10
T C
0
A C
-5
A G
0
A A
10
A A
10
A T
-5
A C
-5
C C
10
C G
-5
C A
-5
C A
-5
C T
0
C C
10
